Content/uploader development
hotosm/oam-docs pull request #36
Opened 2016-11-30 23:14 UTC by nbumbarger

I know a handful of people who've had trouble starting work on the OAM uploader, including myself, because of uncertainty over how the components fit together to get the system up and running. Since what I wanted to write addresses the interconnectedness of the components and also some aspects of getting started, I thought it would be a better fit for here in the docs than in any of the individual READMEs.

2016-12-05 15:58 UTC, danielfdsilva requested changes

2016-12-05 15:58 UTC, danielfdsilva commented on docs/uploader/34_development.md
> +  The script does not fully inherit the variables in the local.env file, so this override is necessary even if it has been populated. Contact a maintainer for the full AWS credentials and database pa
You can do `source local.env` before starting the api to load all the variables.
Also, variables set from ENV, will always override the ones in the config files.

2016-12-05 22:53 UTC, danielfdsilva approved these changes

2016-12-08 17:57 UTC, kamicut commented
@danielfdsilva if you can look at the styling that would be great. What do you think of the wording in this version of the ecosystem docs?

2016-12-08 18:20 UTC, danielfdsilva commented
@kamicut overview looks nice! I think it captures the system well.
I'd say the next thing to do is ensure that the README's of the different components have good instructions on how to be setup (i.e. what are the dependencies they have. For example the uploader would need the uploader-api running).
We could also setup a "development" subpage where we list everything that's needed to setup each "group". I kind of like this approach. Thoughts?

2016-12-08 18:28 UTC, kamicut commented
@danielfdsilva 
1. Is this branch ready to merge? We can open another one for the other development pages. 
2. I think we can have a development subpage, but it should just point to the development subpages of each component. It could be more readable to divide the current ecosystem doc into "Intro" "Catalog Group" "Uploader Group" "Run your own OAM"

2016-12-14 05:39 UTC, smit1678 requested changes
First glance, looks good. Fixed the conflict. Can we complete the Roll Your Own section a bit more?

2016-12-14 18:40 UTC, kamicut commented
@smit1678 I'm wondering how much should be in the "Roll Your Own" section, and how much should be in the individual READMEs. 

My thinking was that we could direct developers to the "development" page in the uploader and catalog sections, which would lead to the READMEs. But that could be a lot of indirection. (e.g: `Roll Your Own -> Uploader Development -> oam-uploader-admin` README)

Another option would be to have all the links in the github READMEs from Roll Your Own, skipping the Uploader Development OAM docs.

What do you think should be in the Roll Your Own section?

2016-12-15 05:10 UTC, smit1678 commented
@kamicut Yes, agreed that we should push towards the READMEs for more detailed setup and configuration for each component. What about just merging Roll Your Own and Development pages?

2016-12-16 19:54 UTC, kamicut commented
@smit1678 I moved the development docs into Roll Your Own, and linked to the READMEs. I have also gone over the individual READMEs and updated anything that is missing for local dev. Let me know if this is enough for ecosystem + local development documentation.

2017-01-18 17:28 UTC, danielfdsilva commented
@smit1678 can we get a final set of eyes on this one to merge?

2017-01-23 10:57 UTC, smit1678 commented
👍  I'm going to merge this and break out separate issues to follow up on a couple ways to improve content based on some feedback.

2017-01-23 10:57 UTC, smit1678 approved these changes

2017-01-23 10:57 UTC, merged